### ISSUE TITLE
Can't find test in the specified module

### ISSUE THREAD

**Issue by IntHelloWorld** [TestingResearchIllinois/idoft#10]
About these lines in pr-data.csv.
I look through the repository on github but I didn't find the corresponding test method.
Then I tried to search through the class name, may be the "module path" of these lines is "innodb-java-reader-cli" instead?

https://github.com/alibaba/innodb-java-reader,24a95d8005d480d460c3004fad89cfa295b9cbb4,innodb-java-reader,com.alibaba.innodb.java.reader.InnodbReaderBootstrapTest.testGenFillingRateHeatmap,ID,,,
https://github.com/alibaba/innodb-java-reader,24a95d8005d480d460c3004fad89cfa295b9cbb4,innodb-java-reader,com.alibaba.innodb.java.reader.InnodbReaderBootstrapTest.testGenLsnHeatmap,ID,,,
https://github.com/alibaba/innodb-java-reader,24a95d8005d480d460c3004fad89cfa295b9cbb4,innodb-java-reader,com.alibaba.innodb.java.reader.InnodbReaderBootstrapTest.testQueryAllDirectIO,ID,,,
https://github.com/alibaba/innodb-java-reader,24a95d8005d480d460c3004fad89cfa295b9cbb4,innodb-java-reader,com.alibaba.innodb.java.reader.InnodbReaderBootstrapTest.testQueryByPrimaryKeyNotExist,OD,,,
https://github.com/alibaba/innodb-java-reader,24a95d8005d480d460c3004fad89cfa295b9cbb4,innodb-java-reader,com.alibaba.innodb.java.reader.InnodbReaderBootstrapTest.testQueryBySecondaryKeySpecifySkOrdinalNegate,ID,,,
https://github.com/alibaba/innodb-java-reader,24a95d8005d480d460c3004fad89cfa295b9cbb4,innodb-java-reader,com.alibaba.innodb.java.reader.InnodbReaderBootstrapTest.testQueryBySecondaryKeySpecifySkRootPageNumberNegate,ID,,,
https://github.com/alibaba/innodb-java-reader,24a95d8005d480d460c3004fad89cfa295b9cbb4,innodb-java-reader,com.alibaba.innodb.java.reader.InnodbReaderBootstrapTest.testRangeQueryByPrimaryKeyNegative,ID,,,

**Comment by IntHelloWorld** [comment]
Btw, there is a '$' in line 169, which violate the format.

**Comment by winglam** [comment]
Thank you for the report. Can you please open a PR with your name so that you can get credit for finding these problems?

**Comment by IntHelloWorld** [comment]
Of course! I'll figure out if there are other problematic lines and open a PR after that.

**Comment by winglam** [comment]
Thanks, I look forward to the PR. You can also open a PR with just these tests now and then open more PRs later if you find other tests.

**Comment by IntHelloWorld** [comment]
@winglam I have created a PR, hope it's helpful!
