### ISSUE TITLE
where is better to add a python script for automatically checking RepoArchived projects?

### ISSUE THREAD

**Issue by LeoYimingLi** [TestingResearchIllinois/idoft#150]
Hi, I write a python script to check the projects in pr-data.cvs whether are RepoArchived or not. I think it could be helpful to upload here, but where can I add it in this repo ? 
the running result is like:
![image](https://user-images.githubusercontent.com/46290389/139995976-984ad024-6a44-49da-8a61-e9b7c3763504.png)

**Comment by winglam** [comment]
Thanks for working on such a script!

Please make a PR and add the script to the following directory.
https://github.com/TestingResearchIllinois/idoft/tree/main/auto-update-dataset

Please be sure to include a detailed readme for how we can use the script.

**Comment by LeoYimingLi** [comment]
get it:)  the PR link: https://github.com/TestingResearchIllinois/idoft/pull/156
