### ISSUE TITLE
Ill-formed entries in pr-data.csv

### ISSUE THREAD

**Issue by ghilesZ** [TestingResearchIllinois/idoft#223]
Hi,
It seems to me that from line [1083](https://github.com/TestingResearchIllinois/idoft/blob/main/pr-data.csv#L1083l) to 1088 of the file pr-data.csv the entries are badly formatted. Here are the incriminated lines.  

````
https://github.com/ctco/cukes,b483e1a8f261b80a66291a42fc455256b0b5059c,cukes-core,"lv.ctco.cukes.core.RunCukesTest.When let variable ""var1"" to be random password with length 8",NOD,,,
https://github.com/ctco/cukes,b483e1a8f261b80a66291a42fc455256b0b5059c,cukes-oauth-sample,"lv.ctco.cukes.oauth.sample.RunCukesOAuthTest.And response contains ""Read success""",NOD,,,
https://github.com/ctco/cukes,b483e1a8f261b80a66291a42fc455256b0b5059c,cukes-rabbitmq-sample,"lv.ctco.cukes.rabbitmq.RunCukesRabbmitMQTest.And content-type is ""application/json""",NOD,,,
https://github.com/ctco/cukes,b483e1a8f261b80a66291a42fc455256b0b5059c,cukes-samples/cukes-rest-sample,"lv.ctco.cukes.rest.run.RunCustomCukesTest.* mock response will have header ""expected"" with value ""hello""",NOD,,,
https://github.com/ctco/cukes,b483e1a8f261b80a66291a42fc455256b0b5059c,cukes-http,lv.ctco.cukes.http.facade.HttpAssertionFacadeImplTest.shouldReturnBodyWhenEnabledAndNoMax,OD-Vic,Accepted,https://github.com/ctco/cukes/pull/157,
https://github.com/ctco/cukes,b483e1a8f261b80a66291a42fc455256b0b5059c,cukes-samples/cukes-plugin-sample,lv.ctco.cukes.plugins.RunCukesTest.Given wait for 1 second,NOD,,,
````

The fourth column, which is supposed to contain the Fully-Qualified Test Name (packageName.ClassName.methodName) contains weird values i.e: `When let variable ""var1"" to be random password with length 8"`. 
It looks like some code escaped from [here](https://github.com/ctco/cukes/blob/d3a787ca6a9e679edd23d8b6cc8f89e8364284b8/cukes-core/src/main/java/lv/ctco/cukes/core/api/GivenSteps.java#L36) and found its way in the dataset.

I dont know how to fix this beside simply removing the lines.

**Comment by darko-marinov** [comment]
The fourth column is actually test description and in some cases, such as those that you listed or parameterized tests, is not a fully-qualified name of the method. What processing are you doing on the dataset? Can you just ignore the rows that are not a fully-qualified name? Or are you trying to rerun these tests?

**Comment by ghilesZ** [comment]
> The fourth column is actually test description and in some cases, such as those that you listed or parameterized tests, is not a fully-qualified name of the method.

Ok, so if this is not a bug, it should probably be mentioned [here](http://mir.cs.illinois.edu/flakytests/summary.html)

> What processing are you doing on the dataset? Can you just ignore the rows that are not a fully-qualified name? Or are you trying to rerun these tests?

My processing was to download all the Java files containing the flaky methods,(for studying purposes), that's why i needed the fully qualified name but yes i'll simply ignore those tests for now.

**Comment by darko-marinov** [comment]
Thanks for the report, @ghilesZ.

@winglam, can you please update the website?

**Comment by winglam** [comment]
Thanks, everyone for raising this issue and the discussion. I have updated the readme to clarify that the test description is allowed for this column now.
https://github.com/TestingResearchIllinois/idoft/commit/def35c1c4c3d5d87a581064ec0c9334885d1a095
