### ISSUE TITLE
apache/jackrabbit-oak, bd0526a24f221413976281ccbb0df95170fccc76, oak-blob-plugins

### ISSUE THREAD

**Issue by sliu-UIUC** [TestingResearchIllinois/idoft#88]
Here is the link of the flaky-lists.json for 17 OD tests newly detected in submodule `oak-blob-plugins` of https://github.com/apache/jackrabbit-oak on the SHA d0526a24f221413976281ccbb0df95170fccc76. 
For the ease of upload, the file has been changed to `.txt` format
[flaky-lists-jackrabbit-oak.txt](https://github.com/TestingResearchIllinois/idoft/files/7272103/flaky-lists-jackrabbit-oak.txt)

Here is the original order txt file: 
[original-order.txt](https://github.com/TestingResearchIllinois/idoft/files/7274135/original-order.txt)

**Comment by darko-marinov** [comment]
Thanks for attaching the files that help in reproducing the failures.
